variables:
  GIT_SUBMODULE_STRATEGY: recursive


#image: gcc
image: ubuntu:18.04

stages:
  - build


before_script:
  - apt update -qq
  - apt -qq -y install lsb
  - apt -qq -y install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qt5-default qttools5-dev-tools qtmultimedia5-dev libqt5opengl5-dev libqt5svg5-dev libfftw3-dev libpulse-dev libasound2-dev
  - apt -qq -y install g++
  - apt -qq -y install git cmake cvs libtool
  - apt -qq -y install libfftw3-dev libsndfile1-dev libpulse-dev

  # - lsb_release -a
  - uname -a
  - cmake --version

build:
  stage: build
  script:
    - pwd
    - git status

    - qmake "CONFIG+=file_sdif file_sdif_static" dfasma.pro;
    - make

    - cd distrib; bash package_getversion.sh; cd ..
    - cd distrib
    - bash package_deb.sh ../dfasma
    - export PACKAGENAME=dfasma_`bash package_getversion.sh`\_$ARCH.deb
    - echo $PACKAGENAME
    - ls -l $PWD/$PACKAGENAME
