#!/bin/bash

DFASMA_VERSION=`git describe --tags --always`

echo "// This file is generated by versions.h" > versions.h

echo "#define DFASMA_VERSION \"$DFASMA_VERSION\"" >> versions.h

echo "#define FFTREAL_VERSION \"2.11\" // This is the current built-in version" >> versions.h

echo "#define FFTW_VERSION \"3\" // Used interface's version" >> versions.h
